name = "OVERLAY2022"
uuid = "ef129194-a226-4d8a-b575-62ba8eb377d7"
authors = ["Mauro MILELLA", "Giovanni PAGLIARINI", "Andrea PARADISO", "Eduard I. STAN"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SoleAlphabets = "bc461207-1577-452f-bfcc-57c11e9f51b7"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
SoleModelChecking = "f545febf-9d2a-4ce1-b6cd-bbab897c9eb4"
SoleTraits = "f0cd7361-857b-4e5b-8aae-3a26fab9cfa9"
SoleWorlds = "d5f91e23-4e14-4856-a67b-b38735209aab"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
